version: 2
jobs:
  build:
    working_directory: ~/working_directory


    docker:
      - image: circleci/node:6.11-browsers
        env:
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome
    steps:
      - checkout

      - restore_cache:
          key: v2-npm-dependencies-{{ .Branch }}-{{ checksum "package.json" }}

#      - run:
#          name: Install Google Chrome
#          command: |
#            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#            sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
#            apt-get update
#            apt-get install -y google-chrome-stable
#
#      - run:
#          name: Disable Sandboxing in Chrome
#          command: |
#            sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox --no-sandbox|g' "/opt/google/chrome/google-chrome"

      - run:
          name: System information
          command: |
            echo "node $(node -v)"
            echo "npm v$(npm --version)"

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: v2-npm-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests
          command: npm test


